version: '3.8'
services:
  postgres-db:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    container_name: redis
    hostname: localhost
    image: redis
    ports:
      - "6379:6379"
