spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/example
    password: postgres
    username: postgres
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
  jpa:
    open-in-view: false

cache:
  names: user_filter
  default:
    minutes:
      ttl: 120